project:
  type: website

website:
  title: "Final Project"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - data-exploration.qmd
      - causal-assumptions.qmd
      - final-model.qmd
      - sensitivity-data.qmd
      - citation.qmd

format:
  html:
    theme: cosmo
    css: styles.css



